1) Given the array split the array at the middle (if it is odd length consider next higher integer), add reverse the array.

Ex:
if input is [12,10,5,6,52,36] 
output should be [6,52,36,12,10,5]

if input is  [12,10,5,6,52,36,34]
output should be [6,52,36,34,12,10,5]

In [278]:
import math
# Complete this function to get the desired result
def reverseatCenter(arr):
    n = len(arr)
    temp = arr.copy()
    if int(n%2) == 0:
        for i in range(0,int(n/2)):
            arr[i] = temp[int(n/2)+i]
        for i in range(int(n/2),n):
            arr[i] = temp[i-int(n/2)]
    
    else:
        for i in range(0,int((n+1)/2)):
            arr[i] = temp[int((n+1)/2)+i-1]
        for i in range(int((n+1)/2),n):
            arr[i] = temp[i-int((n+1)/2)]
    return arr

In [280]:
# Print wroking examples
arr1 = [12,10,5,6,52,36]
print(reverseatCenter(arr1))
arr2 = [12,10,5,6,52,36,34]
print(reverseatCenter(arr2))

[6, 52, 36, 12, 10, 5]
[6, 52, 36, 34, 12, 10, 5]


2) Given a list of numbers, return a list where all adjacent duplicate elements have been removed.

Ex:

2, 2, 2, 3, 2 returns 2, 3, 2.

In [52]:
# Complete the function to get the desired result

def remove_adjacent(nums):
    i = 1
    while i < len(nums):    
        if nums[i] == nums[i-1]:
            nums.pop()
            i -= 1 
        i += 1
    return nums

In [51]:
# Print working examples
print(remove_adjacent([2,2,2,3,2]))

[2, 3, 2]


3) given matrix of 7x7 full of ones, create a square with given side length (center same as original square(7x7)) replace ones with zeors at the edges for example,



$$
\begin{align}
A = \begin{bmatrix}
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
\end{bmatrix}
\end{align}
$$
After modification
$$
\begin{align}
A = \begin{bmatrix}
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 0 & 0 & 0 & 1 & 1\\
1 & 1 & 0 & 1 & 0 & 1 & 1\\
1 & 1 & 0 & 0 & 0 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
1 & 1 & 1 & 1 & 1 & 1 & 1\\
\end{bmatrix}
\end{align}
$$

In [44]:
import numpy as np
# write programm to get the desired result
def create_square(size):
    A = np.ones((7,7))
    if size == 7:
        A = np.zeros((7,7))
    elif size == 5:
        A = np.zeros((7,7))
        A[0,:] = 1
        A[6,:] = 1
        A[:,6] = 1
        A[:,0] = 1
    else:
        A[2:5,2:5] = 0
        
    A[3,3] = 1
    
    return A

In [48]:
#Print working examples
print(create_square(3))
print("\n")
print(create_square(5))
print("\n")
print(create_square(7))

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 1. 1.]
 [1. 1. 0. 1. 0. 1. 1.]
 [1. 1. 0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


4) Paragraph present in data.txt is encoded such that each alphabet in word is incremented to next ascii value. Decode the paragraph present in the data_encoded.txt (Hint: decrease the ascii value of each character in the word)


In [332]:
with open ("data_encoded.txt", "r") as myfile:
    data=myfile.read()
    data = list(data) #Making strings mutable
    for i in range(len(data)):
        if data[i] != ' ':
            data[i] = chr(ord(str(data[i]))-1)
    ''.join(data)
    
def convert(s): 
  
    # initialization of string to "" 
    new = "" 
  
    # traverse in the string  
    for x in s: 
        new += x  
  
    # return string  
    return new 

print(convert(data)) 

data analysis is a process of inspecting, cleansing, transforming and modeling data with the goal of discovering useful information, informing conclusions and supporting decision-making. data analysis has multiple facets and approaches, encompassing diverse techniques under a variety of names, and is used in different business, science, and social science domains. in today's business world, data analysis plays a role in making decisions more scientific and helping businesses operate more effectively.
